### ISSUE TITLE
[BUG] Hiding an objective doesn't hide it

### ISSUE THREAD

**Issue by scooper4711** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#10]
**Module Version:** v0.5.3

**Describe the bug**
This is a copy of https://github.com/Forien/foundryvtt-forien-quest-log/issues/113. There was zero acknowledgement of this bug over there (perhaps the Leauge doesn't have permission?) so I wanted to copy it over here to see if this could get some attention.

Hiding an objective by pressing the "eye-con" doesn't actually hide it from players. I have all my players configured as "trusted players" and they can still see the hidden objectives.

**To Reproduce**
1. Go to 'quest log"
2. Click on 'new quest' & fill in some info
3. click on new objective. Fill in info and make it hidden.
4. The quest should be "active"
5. log in as a trusted player and view the quest. You can see the objective

**Expected behavior**
Hidden objectives should be visible only to the GM and assistant GMs until such a time as the objective is made visible.

**Screenshots**
<img width="931" alt="Screen Shot 2020-12-29 at 6 39 15 PM" src="https://user-images.githubusercontent.com/1970249/103324543-2cb0ac80-4a05-11eb-9c1f-a45f59348ad3.png">

**Browser:**
 - Chrome

**Foundry Version:** 
0.7.8

**Game System:** 
HarnMaster

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by Kayne** [comment]
I found out that it works as expected when you have "Allow Players to edit Quest Details" **disabled** (as in my screenshot below).
So, if you don't really need it, it may be an work around for a time being to hide hidden quests.

<img width="276" alt="Zrzut ekranu 2021-02-12 o 17 19 24" src="https://user-images.githubusercontent.com/1120451/107793337-7572b980-6d56-11eb-938d-2d9d32f481f9.png">

**Comment by scooper4711** [comment]
Agreed. I've updated my quests and they work as I want.
