### ISSUE TITLE
Text editor provides HTML access

### ISSUE THREAD

**Issue by atnoslen** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#108]
It appears editing quests uses a different editor than TinyMCE.  The ability to edit raw HTML is missing.  I edit the raw HTML to manually fix secret blocks (they tend to not group properly) and assign an ID to unhide programmatically.  Example:

Unhide Quest Dialog
```
const questId = args[0];
const taskName = args[1];
const dialogId = args[2];

const QuestAPI = game.modules.get('forien-quest-log').public.QuestAPI;

const quest = QuestAPI.DB.getQuest(questId);

let content = $('<div>' + quest.description + '</div>');
$('#'+dialogId, content).removeClass('secret');

quest.description = content.html();

for (let index = 0; index < quest.tasks.length; index++) {
   if (quest.tasks[index].name === taskName) {
      quest.tasks[index].completed = true;
      quest.tasks[index].failed = false;
      quest.tasks[index].hidden = false;
      break;
   }
}

await quest.save();
QuestAPI.open({questId});
Hooks.call('ForienQuestLog.Open.QuestLog');
```

Current workflow is to have a script that sets the HTML directly (which is moderately painful).

1. Create journal entry
2. Develop description, including HTML metadata
3. Copy full HTML
4. Bring to text editor
5. Escape doublequotes
6. Copy into variable in following script
7. Execute

```
const questId = "jPTIu0gcAnwTM3Vq";

const QuestAPI = game.modules.get('forien-quest-log').public.QuestAPI;

const quest = QuestAPI.DB.getQuest(questId);

var description = "<p>blah blah @JournalEntry[KsGlxpB2LUjzkIqm]{Jourlan Link}</p><section id=\"hJ1WiGEFrty3Ih4M\" class=\"secret\"><h3>Who are the Bumblebrashers, and why are you worried about them?</h3><blockquote><p>&ldquo;The @JournalEntry[qGYdsha42IzzT669]{Bumblebrasher Tribe} are a tribe of goblins who have, for years now, lived peacefully and in isolation in @JournalEntry[dRYSSYDVFrxTehja]{Citadel Altaerein}, the former @JournalEntry[4CXYf6SNzR3IPa1r]{Hellknight} keep on the hill just outside of town. Typically, every two weeks I meet with @JournalEntry[BBYw0M2mWYL7lHHx]{Helba}, the tribe&rsquo;s chieftain, on the road outside the keep. We discuss news, and I convey the town&rsquo;s interests and hear any concerns that the tribe might wish me to bring before the council. It is a relationship of utmost importance, and @JournalEntry[BBYw0M2mWYL7lHHx]{Helba} is normally punctual. But she has missed our previous two meetings, and I have seen plumes of smoke coming from the top of the citadel. The smoke is a chalky red in color&mdash;the tribe&rsquo;s traditional color of distress. I fear that the @JournalEntry[qGYdsha42IzzT669]{Bumblebrashers} are in danger, or that something dire has befallen them. It has sickened me with worry.&rdquo;</p></blockquote></section>"

quest.description = description;

await quest.save();
```

As one can imagine, the longer the entry, the harder that becomes to ensure data integrity.

I can then create an Advanced Macro to unhide that section of text and other actions as a result of that dialog, such as unlocking journal entries (changing their permissions to observer):

```
{{macro "Unhide Quest Dialog" "jPTIu0gcAnwTM3Vq" "Ask about the Bumblebrashers" "hJ1WiGEFrty3Ih4M"}}
{{macro "Unlock - Bumblebrasher Tribe"}}
{{macro "Unlock - Helba"}}
```

Overall, this allows a history of dialog during quest start, and might result in journal entries / hints unlocked for the players.  Embedding the linking helps keep searching to a minimum.

**Comment by typhonrt** [comment]
So editing the source code is currently removed for XSS security reasons. Especially with player editing of quests to prevent malicious script entry. IE a player puts a poison script into the description then when a GM opens the quest it is run with GM privilege. 

Of course your macros and such have also shown a current weakness between wanting the QuestAPI / DB access to be open / available particularly to 3rd party modules and such, but also making things available for direct manipulation by those players w/ edit privileges who are savvy enough.

This isn't a problem necessarily for the GM who hopefully won't create malicious scripts to run on their players machines, but the reverse case that can nuke a world with not a lot of code.

I will be conferring with the Foundry core team on how to best run content filtering on quest data. Content filtering of the journal entry content field was added in `0.8.6` to prevent XSS scenarios. Quest data presently is not run through any content filtering, but it may start to receive this treatment in an update soon. 

I suppose the good news is that it may then be able to return the source code editing functionality, but this is in a holding pattern.

**Comment by atnoslen** [comment]
Understood.  I hadn't considered quests with player edit capability (I'm not doing this myself).  Completely makes sense, though I do know when editing a JournalEntry it removes any <script> element.  I'm sure Atropos could extend a scrubber to modules to ensure a holistic approach to content filtering.

In the mean time, manual updates!

**Comment by typhonrt** [comment]
Indeed indeed.. I just posted a request for implementing client side scrubbing to be added to FormApplication and or to `foundry.utils`. I'll close this one.. :O It's actually kind of a tough problem to solve as there are so many ways to defeat regex based solutions, so indeed having something Foundry provided for client use would be fantastic.
