### ISSUE TITLE
Improvements to machine translated French translation

### ISSUE THREAD

**Issue by anthonyronda** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#111]
Due to being unable to contact the previous translators for the French translation for #42, we had to replace the French translation with a machine translation. Until we find someone who can write their own French translation for Forien's Quest Log, quality of the French translation may be degraded. Reference the current machine translation as needed, but the former translations can't be referenced in your contribution.

**Comment by typhonrt** [comment]
Uh... `@rectulo` from mothership  `translations` channel provided a fresh French translation which got into `0.7.5`:
See here [on Discord](https://discord.com/channels/170995199584108546/596018541879230476/865534541287522314)

@Fallayn committed the new German translation. 

I should probably reverse the changes to the French translation to rectulo's.

**Comment by anthonyronda** [comment]
There was an error, sorry! I see it's already reverted
