### ISSUE TITLE
Add 10pt / 12pt as default font size styling.

### ISSUE THREAD

**Issue by typhonrt** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#113]
Alas in the selection of default font sizes for text styling indeed it is relevant to provide 10pt / 12pt as options for smaller text styling by default. The minimum size in the `0.7.6` release of FQL is 14pt which can be too large for some GM / users in regard to font size. 

The solution is to add 10 / 12pt as options for font size. 

However, for anyone that sees this issue you can manually adjust font sizes with the source code editor if necessary to any size including smaller. Please see this image on how you might accomplish this task presently:

![image](https://user-images.githubusercontent.com/311473/128624148-d485a750-ee53-42a0-86d6-4cbf128b57c0.png)

The `0.7.7` release of FQL will add 10 / 12pt as default font sizes so this will be easy to accomplish in the font selection tools provided in the toolbar. For now though please edit the inline font size styles to a smaller size as necessary.

**Comment by typhonrt** [comment]
Another technical option for now is to open the `/forien-quest-log/src/control/TinyMCE.js` file and edit line 170 to add the 10pt / 12pt options. 

![image](https://user-images.githubusercontent.com/311473/128625086-986bfa01-9d5a-46db-b216-7ec5473479fd.png)

This would make this line of code: 
`const s_DEFAULT_FONT_SIZE = '10pt 12pt 14pt 16pt 18pt 22pt 28pt 32pt 36pt 42pt 48pt 64pt';`

The benefit of doing this is that it would expose the smaller text sizes in options in the interactive TinyMCE editor. This is the change I'll make in the `0.7.7` release of FQL. If you make this change right now and start editing content there will be no ramifications when you upgrade to FQL `0.7.7`.

**Comment by Shuggaloaf** [comment]
Hi Typhonrt, I'm not sure if this is the same issue or if what I'm describing is another issue. I have edited TinyMCE.js per instructions above and have rebooted foundry. I am still seeing very large font size when editing a quest, but a smaller, normal size font after I save. 

For example here is what I see when editing:
![image](https://user-images.githubusercontent.com/79543184/130299902-e7b759ad-b741-466e-b900-62732ecca76b.png)

And here is what it looks like after hitting save:
![image](https://user-images.githubusercontent.com/79543184/130299923-38304dd6-700e-4235-a1c0-5f6bb1d89779.png)

Is this the same issue? If not, are you aware of this and should I put in a new ticket?

Thanks

**Comment by typhonrt** [comment]
Hi @Shuggaloaf. Indeed that is a flaw in the CSS that has already been corrected though not tracked in an issue presently. The default font size was set for the editing, but when you view the edited result the font size doesn't have the matching CSS and therefore is smaller; I didn't recognize what was happening until after `0.7.6` was released. This is already fixed in `0.7.7`. Not exactly related to this issue, but `0.7.7` does tidy up some of the TinyMCE aspects that were started in `0.7.6`. The way to fix this now is to explicitly set a font size on a block of text and it will be the same in the editor and afterward. 

One of the other areas that was fixed with TinyMCE is removing the default margins on <p> / paragraph tags which is the TinyMCE default and then properly getting line-spacing to work with an additional toolbar option to handle things properly. This may adjust folks content, but I hope it doesn't cause too much trouble as the changes in `0.7.7` are correct for this matter and allow more flexibility.

**Comment by typhonrt** [comment]
Released in `0.7.7`
