### ISSUE TITLE
Apostrophes in quest names / objectives become quotation marks[BUG]

### ISSUE THREAD

**Issue by Kurrgan** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#114]
**Module Version:** v0.7.6

**Describe the bug**
If you edit a quest name, any apostrophes in it will automatically convert to quotation marks. 
This behavior happens in the objectives list as well.

**To Reproduce**
1. Create quest named *Example's Quest*
2. Save Quest and reopen it
3. Click the edit title button
4. Quest name will change to *Example"s Quest*

**Note:** If you change the quotation marks back to apostrophes before saving it will save as apostrophes as originally intended.

**Browser:**
 - Chrome Version 92.0.4515.131 (Official Build) (64-bit)

**Foundry Version:** 0.8.8

**Game System:** 5e

**Comment by typhonrt** [comment]
Indeed this is an issue. Not sure why I didn't catch this before, but such is life. It likely was around from `0.7.x` series of releases. Thanks for reporting @Kurrgan!

**Comment by typhonrt** [comment]
Released in `0.7.7`
