### ISSUE TITLE
Change how link in Quest Tracker looks like

### ISSUE THREAD

**Issue by happy-cujo** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#120]
The basic entity-link styling doesn't look nice when displayed in Quest Tracker.

Reasoning. It's nice to have quick access to linked resource, but that doesn't mean the visual aesthetics need to be affected by it. In journals it make sense to make them stand out, because it's helpful to pin point them in a big wall of text. In Quest Tracker that indicator can be less glaring.

Ideas (`Ghouls'` link is presented with different styles, the Ghast link is left untouched for reference purposes):

- Basic link with underline as indicator
![obraz](https://user-images.githubusercontent.com/15898113/131325807-5e5ea212-07bb-402b-a7d0-278b7cbfb84c.png)

- Basic link with different color as indicator
![obraz](https://user-images.githubusercontent.com/15898113/131326145-7b10fc9c-3a48-46ce-a37a-db02a406e7b5.png)

- Basic link + icon
![obraz](https://user-images.githubusercontent.com/15898113/131326262-d43f825b-2f56-4f78-aa3a-0e08ff27f5b6.png)

- Basic link + icon + different color
![obraz](https://user-images.githubusercontent.com/15898113/131326543-c8991829-ec0c-4563-a711-ff60e1bf62fb.png)

There is a lot of other combination possible, but those are the simplest ones.

**Comment by typhonrt** [comment]
Hi @happy-cujo. Thanks again for the enhancement idea. As things go the default will remain, but I added support for `lib-themer` to change entity link background with matching contrast text which is either light / dark. 

`lib-themer` is not released yet, but FQL will support it and this will allow custom theming of the quest tracker including background color / image / text color. 

Check out the link modification ability: 
![quest-tracker-entity-link-lib-themer](https://user-images.githubusercontent.com/311473/131629381-5dd2c766-dc08-4899-9356-3b732c7ed346.gif)

**Comment by typhonrt** [comment]
Released in `0.7.7`; however, pending release of Lib Themer which is in closed beta. Check out the `0.7.7` video to see it in action: 
https://www.youtube.com/watch?v=lfSYJXVQAcE&t=1665s
