### ISSUE TITLE
Add option to auto match height for Quest Tracker

### ISSUE THREAD

**Issue by happy-cujo** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#121]
Add configuration option that allows Quest Tracker to match content height with a limit of the space left to the bottom of the page. This should not affect the width that was set by a user. 

If you set it up to if would be nice to have Quest Tracker auto-adjust to the quests that it is displaying to prevent big gray opaque space or hiding quests because of scroll bar. 

Hidden feature: enable "auto-adjust" when double clicking the resize handle. Disable it when user manually resized something or double clicks again.

Example:
Basic view:
![obraz](https://user-images.githubusercontent.com/15898113/131329179-ad9d9cfa-e433-4040-ae38-175ba7128698.png)
What's left after you remove/hide one of the quests:
![obraz](https://user-images.githubusercontent.com/15898113/131329222-54d33ff8-a277-46f8-92f2-da5d5ddbe1ba.png)
How should it be displayed (height should be automatically adjusted, ignore different width it wasn't an intended change)
![obraz](https://user-images.githubusercontent.com/15898113/131329290-f52c9eb8-29fe-4e19-a457-a9dae8b69f39.png)
It should behave in similar way when new quests shows up - the tracker should expand.

**Comment by typhonrt** [comment]
Hi @happy-cujo. Thanks for checking out the RC1 / release candidate. You have the module setting "Quest Tracker Resizable" set to true. Unselect it like below and the Quest Tracker auto-resizes. 

![image](https://user-images.githubusercontent.com/311473/131330753-29791834-cf6f-4c66-84ce-e55e953ea52e.png)

**Comment by happy-cujo** [comment]
Oh, silly me. That's awesome! So this can be closed then.

**Comment by typhonrt** [comment]
Also if you want to easily switch between resizable and auto there is a macro you can drop into the hotbar in the player macros.
