### ISSUE TITLE
Enable right click menu for Quest Tracker entries

### ISSUE THREAD

**Issue by happy-cujo** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#122]
Mostly for GM (changing quest status, copying links) but also for Players (marking quest as primary).

Small qol that removes one additional step that require you to one Quest Entry.

**Comment by typhonrt** [comment]
Thanks for the suggestion @happy-cujo! I got this in and it works great. Just as a note only GMs can set the primary quest; not players.

**Comment by typhonrt** [comment]
Released in `0.7.7`
