### ISSUE TITLE
0.8.x compatbitility

### ISSUE THREAD

**Issue by akrigline** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#13]
> I've been doing some testing in 0.8.0 and I regret to say that Forien's Quest Log is going to require either some extensive re-work or de-listing in order to achieve compatibility with the new major version because of some of the "tricks" it was doing to spoof a Quest entity type

From Atropos on discord.

**Comment by typhonrt** [comment]
I'm interested in taking a look.. It might be a few weeks, but definitely need this module.

**Comment by xdy** [comment]
I just got a patch on Discord from Eadorin that looks promising (https://discord.com/channels/732325252788387980/836274770332483634/849007565651705866).
I'll fix the remaining warnings and get a 0.8-only release out as soon as I can. (The left sidebar quill doesn't work, so I might disable that on the upcoming release unless I figure out what's wrong. But, as FQL can be opened from the Journal Entries tab, I figure that's not a show-stopper)

**Comment by xdy** [comment]
See the branch. For now I've set it as 0.8 only, will take a look tomorrow to see if it actually works on 0.7 also.
Either way, unless I come across a showstopper, I'll probably put out a release tomorrow.
