### ISSUE TITLE
[Discussion] New Quest tracker / HUD is missing after recent update (link to video on how to use it)

### ISSUE THREAD

**Issue by ghoulapool** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#131]
**Module Version:** v0.7.7

**Describe the bug**
The quest tracker / HUD, to the top right of the screen, is missing now after this update to 0.7.7.  I've noticed the option to enable the quest tracker isn't in the config either.  Thinking it might have been removed, I came here only to see discussion about how it's been an emphasis of the recent update.  I'm confused.

Notice in screenshot that I have quests, the config doesn't show the quest tracker checkbox on/off, and the top right doesn't display the tracker.

![Screen Shot 2021-09-09 at 12 23 37 PM](https://user-images.githubusercontent.com/36716334/132741775-c95836c4-06ae-420a-9559-d77ecea4a708.png)

**Comment by ghoulapool** [comment]
For what it's worth, I see that resizable is an option.  I've tried toggling that on and off and wonder if somehow it's been resized to non-existent, or hidden somewhere.  Not sure where I'd look to expand that if that's the case.

**Comment by typhonrt** [comment]
Indeed there isn't documentation on the wiki, but you'll find this video going over all the details of the new quest tracker helpful.

https://www.youtube.com/watch?v=lfSYJXVQAcE&t=281s

What you are seeing is not a bug.

**Comment by ghoulapool** [comment]
Thanks!
