### ISSUE TITLE
Gold and Experience points

### ISSUE THREAD

**Issue by Kirkmund** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#15]
Hello, I would like to ask the developer of this module to give coins and experience points as rewards. It's possible?

**Comment by typhonrt** [comment]
Hi @Kirkmund. This is the most requested feature and I'm working on a continuation quest log module that is due out late ~summer. The first big new feature will be currency & XP support. Subscribe to this issue on the new quest log repo to get a notification when it ships. The new quest log will be launched initially then the follow up version will have this new feature. 

https://github.com/typhonjs-fvtt/typhonjs-quest-log/issues/135

I'm going to mark this particular issue on this repo as `Wont Fix` as this is a feature for the new quest log.
