### ISSUE TITLE
[BUG] V10 error

### ISSUE THREAD

**Issue by Petwag** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#17]
I am getting this error : 
```
constants.js:42 Uncaught TypeError: Cannot read properties of undefined (reading 'render')
[Detected 1 package: forien-quest-log]
    at Object.onClick (constants.js:42)
    at SceneControls._onClickTool (foundry.js:66675)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.y.handle (jquery.min.js:2)
onClick @ constants.js:42
_onClickTool @ foundry.js:66675
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

I am on 0.7.9 for Forien and V10.283 for Foundry

**Comment by typhonrt** [comment]
Hi @Petwag... Not a bug as FQL `0.7.10` has not been released yet with v10 support.  Can you let me know if you were able to install FQL from the Foundry package manager?   Alas as things go I don't have access to the League of Extraordinary Foundry Developers Foundry package manager account. You shouldn't be able to install the publicly released `0.7.9` on v10 though it sounds like somehow you have... 

The good news is that I have a release candidate for `0.7.10-rc2` that you can install right now and test on v10 that is fully working. I generally plan to release FQL `0.7.10` this upcoming Monday. It runs on v9 and v10. 

Remove your FQL module and use this link to install the release candidate:
https://github.com/typhonjs-fvtt-scratch/foundryvtt-forien-quest-log/releases/latest/download/module.json

Just remember to once delete your FQL `0.7.10-rc2` module once the public release is available for v10 next week and reinstall it from the Foundry package manager to pick up the actual public release. There shouldn't be any problems from a data perspective, but do back up your data.

**Comment by typhonrt** [comment]
More info about the release candidates of FQL. The latest is `rc2`: 
https://github.com/typhonjs-fvtt-scratch/foundryvtt-forien-quest-log/releases/tag/0.7.10-rc2

**Comment by Petwag** [comment]
Thanks a lot that worked! 
And thanks a lot for the work you are doing on this project

**Comment by typhonrt** [comment]
Right on @Petwag. Just a note that FQL v0.7.10 is publicly released. You can delete / uninstall the release candidate and install the public version.
