### ISSUE TITLE
[BUG]On Chrome, floating quest window doesn't update with new quests

### ISSUE THREAD

**Issue by megahead11** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#19]
**Module Version:** v0.5.6

**Describe the bug**
On chrome, when the GM updates the quest list by making new quests active, and the floating quest window (by rughalt) is open, it doesn't sync up with the changes for other players. The GM will see new quests, but players won't. Additionally, deleting a quest list doesn't remove it from the floating window for the GM.

**To Reproduce**

Have the game open in two instances, one for the player and one for the GM.
1. Add a new quest to the list. It is inactive.
2. Ensure the floating window is displaying (Enable Quest Tracker ON)
3. enable the quest. You'll see the quest doesn't appear on player's screens.

This bug doesn't happen on firefox.

https://i.gyazo.com/f90b60470803f1cef5c6c8b9988f1758.mp4

**Browser:**
Chrome

**Foundry Version:** 0.7.9

**Game System:** DnD5e

**Comment by typhonrt** [comment]
I've done pretty rigorous testing with the new FQL version and all sorts of synching issues are fixed. I'm closing this issue as it pertains to and old version of FQL. Please try the new version when it releases shortly.
