### ISSUE TITLE
GM only tool option

### ISSUE THREAD

**Issue by MarceloCortezz** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#22]
Hi Forien,

I really like your module and I would love to use it as a GM tool only, giving no permission for my players to view this module at all. The reason behind this is for better organization and structure when I'm creating quests, but at the same time, keep players tracking everything they are doing by themselves, and not having a facilitator.

I know that there are ways to hide quests from players, however I'm looking forward to use all tabs for GM purposes only.

**Comment by typhonrt** [comment]
Great feature enhancement.. I got it into the forthcoming new FQL version to be released shortly. The image below shows two new configuration options for GMs. To accomplish a private FQL for GM users set default quest permission to "None" and check "Hide Quest Log from players". 

![image](https://user-images.githubusercontent.com/311473/122675891-61214c00-d190-11eb-9e6a-28ef6dbe12ce.png)
