### ISSUE TITLE
[BUG] Possible compatibility issue with GURPS

### ISSUE THREAD

**Issue by cefasheli** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#25]
**Module Version:** v0.5.7

On new launched GGA V.0.9.6 we can drag new itens made to a quest but we can not drag this item to a character sheet.

I'm using Brave, Chrome and Firefox with no modules ( to test it)
Foundry 0.7.9
Gurps Game Aid 0.9.6

**Comment by anthonyronda** [comment]
Hiya, thanks for submitting an issue. I will let another contributor investigate, but in the meantime could you describe the steps you take when you're experiencing the bug?

If you press F12 after performing those steps, does any red error text appear in the console display?

If so please copy that text to your reply here as well

**Comment by typhonrt** [comment]
Good news... I have fixed this for the forthcoming latest version of FQL. I also have noticed a deficiency in how Gurps handles item drops and have posted an issue on their tracker.
