### ISSUE TITLE
Quest Tracker Enhancement Suggestions

### ISSUE THREAD

**Issue by Shuggaloaf** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#26]
I really like the new Tracker HUD, but GM and Players don't need/want to see it all the time. 
Another nice-to-have would be an option to only display Quest Titles and hide tasks (as it can look quite messy with a lot of crossed out tasks). 

So I would like to request the following two enhancements:
(1) A toggle (macro would be perfect) to toggle the quest tracker HUD on and off easily 
> _If there is a relatively easy way to already do this through a macro, or if there is an entity that could be marked as hidden = true, I would really appreciate if someone could share._ 

(2) Quests Tasks: 
_Preferred:_ right-click (or other) on Quest Title to collapse/un-collapse all info under that quest.
_Alternate:_ An option in settings to choose whether or not to display Quest tasks  

> **_EDIT for (2):_** Just noticed the toggle in the toolbar that brings up a Tracker window. That same collapse/uncollapse functionality would exactly what I'm talking about, just with the onscreen HUD. However finding this other option is a great work-around for now. Ultimately I'd still like to see the HUD be able to do this as having the quests on screen, in a player's face, is desirable.

Finally thank you very much to Forien for the original work and to everyone at the LOFD for keeping this alive!

**Comment by typhonrt** [comment]
Got you covered; great enhancement idea! There is now a client option for showing tasks. And even better. For GM hidden tasks are shown in grey and the task totals are shown to the right.  The left hand of the image below is the GM screen and on the right hand is a logged in client / user with the tasks hidden in the quest tracker. Also note that child subquests are listed in the quest tracker now. :D 

This will be out in the next release of FQL. 

![image](https://user-images.githubusercontent.com/311473/122682808-7312e700-d1b0-11eb-8954-4ffbfe369842.png)

**Comment by Shuggaloaf** [comment]
Thanks @typhonrt! Glad you liked the idea. This should help make things a lot cleaner for the players and I like the coloring difference for hidden tasks. Appreciate the work!

This probably isn't the appropriate place to ask this, but before opening another Suggestion I thought I would just ask the question - what ordering is used for subquests/tasks? 
I had a bunch of sub-quests and sorting is not alphabetic and it also doesn't seem to be going by the ID either. Like I said I'll probably open a request for it to be alphabetic (or piggyback onto #7) but figured I'd ask first since I could be missing something.

**Comment by Shuggaloaf** [comment]
Thanks for the quick response! Yeah I noticed it was alphabetic when In Progress. I should have mentioned I meant when the main quest was just "available". 
To give an example, what I was trying to do is have some on-going "Alchemist Guild" style "collection" quests where the main quest would be just something like "Available Alchemist Guild Quests", then when they click that, they would be able to scroll through all the available subquests. (Basically just a little something extra they can do along with normal quests. "Oh I need to kill this Basilisk? Well the Alchemist Guild is also looking for some parts so let me check that sub-quests as well".)

These title of these subquests would just basically be the names of monsters that they could harvest parts from. Since there are literally hundreds of possible monsters, it makes sense to set them all up as subquests. (Tasks wouldn't really work here as 1) they are ongoing and can be done multiple times and 2) I like the idea that they can have just the specific subquests they accept show in the tracker, vs 1 quests with hundreds of tasks)  

This is obviously a very specific use case but I could see this being useful for other types of quests as well. It sounds like what you have listed above that you want to do/have done would be a solution to stuff like this. I'll keep an eye out for future releases. 

Thanks again!

**Comment by typhonrt** [comment]
There will be a big update out soon, but indeed sorting of quests is something hopefully the rcos team / summer internship like deal can take a look at over the next two months or so. I actually put into the DB on the update data storage and places for location, priority, and time gathering. IE even though it won't be live in the GUI data when the quest is created, when it is started and when it ended is collected. This data can hopefully be used to sort quests better in the future. My main "job" more or less was to provide a thorough refactor of the code base and get it ready to work well on `0.8.x`.

**Comment by Shuggaloaf** [comment]
>extra data fields for location, priority, and time gathering.

Definitely excited to see this! I commented on issue #21 that I am also was using a "suggested level" designation. Mainly because I have some new players coming from video game RPGs and this is helpful for them (think Witcher 3 style quest log - see screenshot below). If it's not too late to suggest adding a "level" field as well, that could possibly be helpful to some people. But even if not, what you already have added for later implementation is great! 

<img src="https://user-images.githubusercontent.com/79543184/122835317-1f8ebf00-d2be-11eb-84d4-90a403c0710a.png" alt="pic" width="25%"/>
_[Suggested Level] - [Quest Title] - [Location]_
