### ISSUE TITLE
Description for Objectives

### ISSUE THREAD

**Issue by Volksters** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#26]
It would be a great addition to have descriptions or journals link to them for individual objectives.

**Comment by typhonrt** [comment]
You can paste any document links into objectives including links to journals.
Check this section from the FQL video tutorials: 
https://www.youtube.com/watch?v=Dn2iprrcPpY&list=PLHslnNa8QKdD_M29g_Zs0f9zyAUVJ32Ne&index=3&t=459s

If you haven't watched the tutorials there is a lot of good information about the features of FQL. You can examine the video details to get timecode links to topics:
https://www.youtube.com/playlist?list=PLHslnNa8QKdD_M29g_Zs0f9zyAUVJ32Ne

-----

It's a bit quixotic w/ v10 that there is a copy document ID button on the left hand side of document sheets including journals. I wished they included a button to copy the UUID / document link as well. The trick is to open the TinyMCE editor on the quest details page; drag and drop the document you want to link in the objective into the editor then cut / paste that when you start editing an objective.
