### ISSUE TITLE
GM Description Section

### ISSUE THREAD

**Issue by SasugaTV** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#28]
It would be beneficial to have a GM Description & Notes Section that the GM can see and is hidden from the players to keep all the information about a given quest in one neat place.

Sure, we can hide objectives and hide rewards. However, it'd be nice to have any description for the GMs only that might say, "Remember that the one offering this quest hates the party." or "Use the Urban Cave map." or maybe some dialogue to read to the players, or whatever.

Right now, I hide GM notes in the objectives, but finding the objectives I want to reveal to the players can get messy and difficult.

I could see this GM description as either a tab for the description area of the Quest Details window, at the bottom or one of the sides, or whatever. That way, when a player asks me about a given quest, I can pull it up in the Quest Log and see the notes on it along with everything the players see.

**Comment by typhonrt** [comment]
Hi @SasugaTV. I'm going to close this issue as there are separate `GM Notes` tab on the quest details page for this purpose. 

Link to video tutorial on GM Notes:
https://www.youtube.com/watch?v=cakE2a9MedM&list=PLHslnNa8QKdD_M29g_Zs0f9zyAUVJ32Ne&index=1&t=2559s

Useful video tutorials going over all FQL features. Check the video descriptions for timecode links to topics. 
https://www.youtube.com/playlist?list=PLHslnNa8QKdD_M29g_Zs0f9zyAUVJ32Ne
