### ISSUE TITLE
Quest Tracker not showing up

### ISSUE THREAD

**Issue by mfozz** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#29]
NVM, I had to watch the video to find the button. Ignore this.

**Comment by typhonrt** [comment]
Yeah... No worries... You also need to have an active quest for it to display as it will automatically hide when there are no more active quests. The lower of the quest buttons on the left hand nav bar under the journal tab enables / disables the quest tracker. Really handy though are the FQL macros to drop into the hot bar from the macro compendiums added. 

Sounds like you found the video tutorials though... Plenty of topics w/ links in the video descriptions.. 
https://www.youtube.com/playlist?list=PLHslnNa8QKdD_M29g_Zs0f9zyAUVJ32Ne
