### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by DOMtheDM** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#3]
Hi there,

Not sure if I'm missing something but when I try to install using the manifest URL in Foundry I get a "k is not defined" error. When I click on the manifest URL the link takes me to an "error: not found" page.

**Comment by thedoe** [comment]
The URL is incorrect as it is missing the "download" subfolder - use https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/releases/latest/download/module.json

**Comment by xdy** [comment]
This one seems to be fixed in both module.json and readme.md, closing issue. Please make a new issue if this is still a problem.
