### ISSUE TITLE
Hidden Quests

### ISSUE THREAD

**Issue by Rantarian** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#30]
Allowing Hidden Quests: it might be helpful to allow quests to be hidden so that players cannot see them even if they are active. This would give the GM a tool to keep track of things without needing to keep them as inactive. Subquests of a hidden quest should not identify themselves as a subquest.

**Comment by typhonrt** [comment]
Shipped in `0.7.4` which is now available.
