### ISSUE TITLE
Sub-Quests "blocked" by SplashArt

### ISSUE THREAD

**Issue by SeaSaltSong** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#30]
I was just trying to add some sub-quests, and had this issue of the "add an image" covering the button to add them. Here is a screenshot:

![image](https://user-images.githubusercontent.com/117007321/222419658-2279d82e-daee-4dcf-af1c-0e9b98238448.png)

Alternatively, the configure permissions button is mostly hidden, but I can just click the top of it to access.

**Comment by typhonrt** [comment]
That isn't the normal arrangement for FQL / Manage Quest page. My assumption right away is that there is another module that isn't scoping CSS / styles correctly. Try disabling all modules except FQL and report back if you see this problem still. If you can use "Find the Culprit" or another way to figure out which module might be conflicting I'd be glad to open an issue with the offending module.

**Comment by typhonrt** [comment]
@SeaSaltSong. Could you follow up w/ the above request for more information. As mentioned this is likely a problem with another module rather than FQL. If this was a wide spread problem w/ FQL it would receive a lot of reports. I'll move to close this issue w/ no reproduction steps in the next week or so if I don't receive more information. Thanks for your help.

**Comment by SeaSaltSong** [comment]
So sorry, I missed the notification with the first one.

I disabled all modules and still had the issue. It might be an issue with the system I am using, WoD_20:
https://github.com/JohanFalt/Foundry_WoD20

**Comment by typhonrt** [comment]
@SeaSaltSong.. Yep I can confirm it is poor style scoping from the game system. In particular this block of CSS:
https://github.com/JohanFalt/Foundry_WoD20/blob/main/css/wod.css#L447-L458

Unfortunately, the game system does not scope the CSS styles at all so there easily could be conflicts with any modules. 

I have filed a bug with WoD20 game systems linked just above this comment. 

As things go there is not really anything I can do on the FQL side of things, but the system dev can improve their CSS styles.

**Comment by JohanFalt** [comment]
This will be fixed in WoD20 release v2.4.8
