### ISSUE TITLE
Feature: Toggle Quest Visibility

### ISSUE THREAD

**Issue by Abourass** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#33]
Hello! 

First, I'd like to say that as of so far, this is my favorite plugin for Foundry! Tremendously well done! 
Second, while quest checkpoints can be hidden, I'd love the ability to do the same with quest themselves. It'd be lovely to prepare the quest ahead of time, and simply make them visible to them once they stumble into the quest giver. As it is, I can only add the quest at the end of the session or in the middle as to not spoil things.

**Comment by typhonrt** [comment]
Excellent.. Thanks for the nod and writing an issue.  So you do have several ways to control the quest visibility. The first is that you can simply keep a given quest as "inactive" and it is not displayed to the players. You'll be able to see it in the "inactive" tab, but the players don't see that tab. The second way to control quest visibility is by setting ownership permissions on the quest itself. You can hide it from all players or only let specific players see the quest. When a new quest is created it always is in the "inactive" tab and is not seen by the players until you make it "active".

I have a video tutorial series on YouTube that goes over all of the features. The first video covers a lot with follow up videos on newer features. This link will take you to the part discussing permissions which is one way:
https://youtu.be/cakE2a9MedM?list=PLHslnNa8QKdD_M29g_Zs0f9zyAUVJ32Ne&t=2739

Here is a section on quest categories. I'm sure you have played around with this already, but as mentioned you can always have quests that are "inactive" and you can make them active when the quest is given:
https://www.youtube.com/watch?v=cakE2a9MedM&list=PLHslnNa8QKdD_M29g_Zs0f9zyAUVJ32Ne&index=1&t=821s

The full playlist for FQL tutorials is here; check the video descriptions for a list of topic links:
https://www.youtube.com/playlist?list=PLHslnNa8QKdD_M29g_Zs0f9zyAUVJ32Ne

I'm going to close this issue as a "discussion", but if you have any more questions let me know.
