### ISSUE TITLE
[BUG] Enabling module throws Error: "Missing Document initialization type!" - World fails to load properly.

### ISSUE THREAD

**Issue by Rantarian** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#35]
**Module Version:** v0.5.4

**Describe the bug**
Occurs in Foundry 0.8.6. I have successfully reproduced this issue in multiple worlds under multiple systems.
Turning on the module will produce the error:

Uncaught (in promise) Error: Missing Document initialization type!
    at Game.initializeEntities (foundry.js:4315)
    at Game.setupGame (foundry.js:4285)
    at async Game._initializeGameView (foundry.js:5114)

The sidebar and canvas do not load after this.

**To Reproduce**
1. Create a world
2. Activate module
3. View console

**Expected behavior**
Module loads, but more importantly the sidebar and canvas load.

**Screenshots**
None. It's effectively a blank screen.

**Browser:**
 Chrome and Foundry Application

**Foundry Version:** 
0.8.6

**Game System:** 
Multiple

**Additional context**
This is a more complete view of the console log when the module loads.
Foundry VTT | Retrieved and compiled template modules/forien-quest-log/templates/partials/quest-log/tab.html
foundry.js:3589 Foundry VTT | Retrieved and compiled template modules/forien-quest-log/templates/partials/quest-preview/gmnotes.html
foundry.js:3589 Foundry VTT | Retrieved and compiled template modules/forien-quest-log/templates/partials/quest-preview/details.html
foundry.js:3589 Foundry VTT | Retrieved and compiled template modules/forien-quest-log/templates/partials/quest-preview/management.html
foundry.js:3492 Foundry VTT | Loaded localization file lang/en.json
foundry.js:3492 Foundry VTT | Loaded localization file modules/forien-quest-log/lang/en.json
foundry.js:132 Foundry VTT | Unregistered callback for setup hook
foundry.js:4315 Uncaught (in promise) Error: Missing Document initialization type!
    at Game.initializeEntities (foundry.js:4315)
    at Game.setupGame (foundry.js:4285)
    at async Game._initializeGameView (foundry.js:5114)

**Comment by typhonrt** [comment]
Indeed.. I'm going to close this one to.. The old 0.6.0 FQL had many issues w/ Foundry 0.8.6 from not simulating the right API points. I have tested the new FQL across the top 20 game systems and no problems. The release is soon. If you have a problem with the new release let me know and I'll get right on it.
