### ISSUE TITLE
Actor Images do not appear in Quest Log and appear as grey box in Quest Details

### ISSUE THREAD

**Issue by SovietVVinter** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#37]
**Module Version:** v0.0.0

**Describe the bug**
When viewing the quest log, images no longer appear next to quest titles and when viewing the details of a quest, the actor image box is grey.

**To Reproduce**
1. Open the Quest Log and view a tab with quests
2. Open the details of a quest and view the actor image
3. Create a new quest and drag a new actor image
4. Repeat above with same results

**Expected behavior**
Actor images should appear 

**Screenshots**
![image](https://user-images.githubusercontent.com/71097199/120426372-f83b7680-c33d-11eb-88a1-3b2f0faf81b5.png)

**Browser:**
 - 

**Foundry Version:** 
0.8.6
**Game System:** 
D&D 5e 1.3.3
**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by Havoclivekiller** [comment]
I can confirm. Module ver 0.6.0

**Comment by bobziemerman** [comment]
I can confirm that this is still a problem

**Comment by typhonrt** [comment]
It won't be a problem when 0.7.0 launches very shortly. Brand new hotrod coming. I'm going to close this as this is fixed pending release. Linking of actor / items / journals + abstract quest givers fully supports world items and compendium items. actors w/ different prototype tokens can have the image swapped between both. Just a little more patience...

![image](https://user-images.githubusercontent.com/311473/122624706-58c4f600-d056-11eb-974b-8a6956b2cf04.png)
