### ISSUE TITLE
[BUG] Main window not displaying correctly

### ISSUE THREAD

**Issue by Ragesong** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#37]
**Module Version:** v0.0.0

**Describe the bug**
Open up the Quest Log and the quests are appearing in small boxes OVER the navigation tabs for In Progress, Complete, Failed and Inactive

**To Reproduce**
Happens every time I open the quest log in both Firefox and Chrome.

**Expected behavior**
The quests appear in the main window, not over the navigational tabs.

**Screenshots**
![image](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/assets/143223145/f84e0e24-043d-470c-98f2-2cf7e978e504)

**Browser:**
Firefox and Chrome

**Foundry Version:** 
11.308

**Game System:** 
Earthdawn

**Additional context**
Used to work correct before I upgraded to Foundry v11.

**Comment by typhonrt** [comment]
Hi @Ragesong. Thanks for submitting an issue. However, right away my assumption is that this is another game system or module that has improperly scoped CSS that is conflicting with FQL. This happens occasionally from time to time, but is something that must be resolved in the other game system or module that is causing the conflict. Try disabling all other modules that you have installed and only enable FQL. Things should work fine. You then need to enable modules until you find the one that is causing the CSS conflict. I can then file an issue and clearly describe the problem to the maintainer of the package that is causing the conflict.

**Comment by Ragesong** [comment]
Thank you for the quick response. I did some trial and error and found that it appears to be happening with the Earthdawn game system. I logged into my D&D campaign and did not have the same issue following your instructions above. I am pursuing with that game system's designer. Thanks!

**Comment by typhonrt** [comment]
I'll also take a quick look tomorrow as I can pin point aspects that are causing problems with the game system.

**Comment by Ragesong** [comment]
Heard back from the Earthdawn developers; they found the issue and will be releasing the fix in the next release. :)

**Comment by typhonrt** [comment]
Excellent. Glad to hear it was something easy to fix; usually is just a CSS scoping issue. I'll close this issue. Happy questing! :D
