### ISSUE TITLE
[BUG] No Quests can be displayed using the "The Dark Eye" game system

### ISSUE THREAD

**Issue by lorion1985** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#38]
**Module Version:** v0.6.0

If you open the Questlog and create a new quest, the quest will not be displayed in the Questlog. The tabs are hidden in the game system. In other systems the module works fine. Not sure if I need to adress the issue here or in the TDE game system. Other modules work fine within that game system.

**Screenshots**
![forien](https://user-images.githubusercontent.com/79639947/120509479-d63b0600-c3c8-11eb-8193-b8a5865e633d.PNG)

**Browser:**
 - Opera, Firefox, Chrome

**Foundry Version:** 0.8.6

**Game System:** The Dark Eye 2.0.0
But same issue with Foundry 0.7.10 and The Dark Eye 1.4.3

**Comment by xdy** [comment]
If you have any other modules loaded, try disabling them and see if the problem remains. (https://foundryvtt.com/packages/find-the-culprit/ is really helpful in these situations).
Do you get any exceptions - i.e. red text - in the browser console? Use the shortcut Option + ⌘ + J (on macOS), or Shift + CTRL + J (on Windows/Linux).

**Comment by lorion1985** [comment]
Same problem with a blank new world
![image](https://user-images.githubusercontent.com/79639947/120836026-644bf380-c565-11eb-8422-ca8e9a7e347a.png)
Und there is one exception:
![image](https://user-images.githubusercontent.com/79639947/120836152-8cd3ed80-c565-11eb-9e24-7e4a5823d3d2.png)

**Comment by typhonrt** [comment]
Good news the latest PR https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/pull/45 fixes this issue.

In addition to a small CSS tweak... It should be noted that the Dark Eye system has CSS that disables overflow from apps. FQL has tabs that float to the left, but a CSS tweak targeting FQL will be added so they should show up. The next published release of FQL soon should have you sorted.

**Comment by typhonrt** [comment]
Gotcha covered. New release soon.. :D

![image](https://user-images.githubusercontent.com/311473/122627680-f673f180-d065-11eb-9e93-115a04bc655f.png)
