### ISSUE TITLE
Quests are not refreshed when Players log in [Bug]

### ISSUE THREAD

**Issue by Monzetsu-pain** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#38]
**Module Version:** v0.7.12

**Describe the bug**
When I do so off session tweaks to side quests and such, the players will come back into the game with no quests in the log. I have to "edit" the quests while they are in game for them to be able to see that quest. 

**To Reproduce**
1. All players have left the game
2. The DM will edit a Quest from the Quest Log.
3. The players return, that quest is now gone. 

**Expected behavior**
I was hoping the game would auto refresh or at least catch that there are quests available for the characters. 

**Screenshots**
N/A

**Browser:**
 - Opera GX

**Foundry Version:**
V.11 Build 315 

**Game System:** 
5E D&D 3.0.2

**Additional context**
N/A

**Comment by typhonrt** [comment]
Hi @Monzetsu-pain 
If you can clarify exactly what you are doing in step #2: "The DM will edit a Quest from the Quest Log." that helps.

For instance if you happen to create a new quest it won't be started / visible to players yet. If you happen to change other visibility / ownership aspects that could alter what players see. 

I have verified that editing an already active quest visible to players is not removed or hidden from players when a player is logged out. If this were a problem a lot of folks would be writing in as such. 

So yeah.. My guess is that you are creating new quests when players are logged off, but haven't set them to 'active' / started. So when players log in they are not visible.

**Comment by typhonrt** [comment]
Hi @Monzetsu-pain. If you can follow up with the information requested above I'd be glad to try and help you out. Otherwise by next week I'm going to mark this issue as `invalid`. I can't duplicate anything that you suggested in the original post above.

**Comment by typhonrt** [comment]
@Monzetsu-pain just giving you extra time to respond before I close this issue as `invalid` / `no reproduction`. If you feel there is an issue please do follow up and I'll try and help out. If there was a problem like this there are many users of FQL and it would have been reported already.

**Comment by typhonrt** [comment]
I am closing this issue as the initial reporter has not responded to queries for more information. If you feel like this is not the case please respond with the information requested above.
