### ISSUE TITLE
Count Subquests in checkedTasks and totalTasks

### ISSUE THREAD

**Issue by benjamincampbell** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#4]
Would it be worth counting subquests in the total for the checked and totalTasks when being displayed in the Quest log?

If a quest has 2 objectives and 2 subquests, let's say they're all not completed, it currently shows up as 0/2, which is misleading as when you go into the quest you would see 4 items in the Objectives section (2 tasks and 2 subquests).

It seems like this would be an easy improvement that would perhaps clear up some confusion, unless it's by design of course.

**Comment by typhonrt** [comment]
Got this covered in the forthcoming new release of FQL. 

![image](https://user-images.githubusercontent.com/311473/122679060-39d17b80-d19e-11eb-878c-d80277b0eafe.png)
