### ISSUE TITLE
Added Support for Monks Enhanced Journals Module so that it can find the image

### ISSUE THREAD

**Issue by Drazev** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#42]
Monks-enhanced journals is a popular tool that places journal images in a different location. 

I would like to make a minor adjustment that will enable it to find the image when quests use a reference to the monk's enhanced journal. Presently when the enriched attempts to find the image on a monks enhanced journal page it will be undefined and show as blank.

**Comment by JaysonMendoza** [comment]
I have modified the enhancer slightly so that when it finds a journal page it will first attempt to check the monks enhanced journal location and if that returns undefined it will search the normal location.

**Comment by typhonrt** [comment]
In the past MEJ custom journal types were supported prior to any changes in MEJ to store image paths in a custom flag. I only test FQL every core release of Foundry, so not sure when that MEJ change occurred. I'll accept this PR, but modify it accordingly when I work on the v12 FQL release.

**Comment by JaysonMendoza** [comment]
Thank you!
