### ISSUE TITLE
[BUG] Foriens Quest Log not saving quests

### ISSUE THREAD

**Issue by pmatra** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#44]
**Module Version:** v0.6.0

**Describe the bug**
I enter all of my text in the quest log, and hit save, and it doesn't save my quest or the text in the text box.

**To Reproduce**
Open theh quest log
Enter all required fields
Save text
Window closes Cant save quest

**Expected behavior**
saves text and then save quest.

**Screenshots**

**Browser:**
 - Chrome

**Foundry Version:** 
8.6
**Game System:** 
DnD5e
**Additional context**
Add any other context (like other modules installed) about the problem here.
I have 40 other modules installed. Too many too list. They could be a culprit. But I can't see how.

**Comment by typhonrt** [comment]
I have a PR which fixes this issue and allows rich text and all sorts of fancy markup to be entered into quest fields.. 

https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/pull/45

**Comment by xdy** [comment]
Closing as duplicate of #32
