### ISSUE TITLE
Advanced sneak peak: The new FQL is feature complete and can be installed for those eager to try it out. 

### ISSUE THREAD

**Issue by typhonrt** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#50]
Greets all... So I've busted my tail over the past ~1.5 weeks to provide a major overhaul of FQL. My fork is still pending a merge here, but if you are eager to try it out and I'd be very thankful for as many eyes on this as possible before an official package release. There are lot of small and some large enhancements and a bunch of time went into a consistent user experience. I'd be happy to hear of any issues _before_ the next package release. 

If you have Git installed you can clone the fork into the Foundry modules directory via:
`git clone https://github.com/typhonjs-fvtt-scratch/foundryvtt-forien-quest-log.git forien-quest-log`

You can also download a zip file, but make sure to extract it to `forien-quest-log` in the modules directory:
https://github.com/typhonjs-fvtt-scratch/foundryvtt-forien-quest-log/archive/refs/heads/master.zip

If you decide to try the release candidate above I post the obligatory... back up your data warning.. 

I look forward to receiving any feedback and am excited to see what the Rcos team of students will be able to accomplish this summer as they are the lucky bunch who are next up to add enhancements to FQL.

**Comment by typhonrt** [comment]
Some picts.... Out of the box styling that matches the game system. Pictured Dark Eye & Twodsix:

![fql-backgrounds](https://user-images.githubusercontent.com/311473/123003705-7355e280-d368-11eb-90ef-597699c02d85.png)

![image](https://user-images.githubusercontent.com/311473/123004301-4950f000-d369-11eb-91f4-b2d3f9843876.png)

**Comment by rlach** [comment]
I really like it. Quest log got much more useful. I've tried testing all new features, and there are things I've noticed:

Sub-quests appear at the list of objectives regardless of their status. It would be nice if players didn't see sub-quests that are Inactive. Or, alternatively, if GM could reveal them with eye icon, just like other objectives.

Also, it seems it's impossible now to enter actor name to set the quest source.

**Comment by typhonrt** [comment]
> Sub-quests appear at the list of objectives regardless of their status. It would be nice if players didn't see sub-quests that are Inactive. Or, alternatively, if GM could reveal them with eye icon, just like other objectives.

@rlach Right on thanks for trying things out.. You indeed caught a nice one w/ the display of non-started subquests for users! Knick of time too as I'm just finishing up the final clean up of the module. It won't be hard to of course make sure visibility is correct for users so I'm fixing that right now. 

> Also, it seems it's impossible now to enter actor name to set the quest source.

Entering text directly has been removed for the time being as it is not exactly intuitive without some sort of auto-fill in / display of which actors are available as you type. Dragging / dropping sets the correct UUID in the display and it's a UX decision to not use the same field for two different purposes when the manual type in has no feedback.

You can however now drop in actors, items, journal entries from the world database _and_ compendiums, so functionality is expanded in what can be set as a quest giver.

**Comment by rlach** [comment]
I see, that makes sense for text entering. It was usable only for short names, and for fantasy games... Well, let's say they often are not.

**Comment by typhonrt** [comment]
I think it is a good feature for the RCOS team who are going to be working with FQL via a summer internship to evaluate. What I think makes sense is two add a separate smaller text box right justified on the same line and have some sort of auto-complete functionality hooked up. That could work.

**Comment by Xystem4** [comment]
Yep, we (the RCOS team) have been playing around with the module, and your current fork in specific the past few days, and taking notes of features we might add or enhance in some way once you're all merged. Adding in alternatives to drag-and-drop was one of the big ones on my radar! (Dragging on a mousepad disagrees with my tendonitis). There will probably be a bit of a flood of enhancement suggestions after the merge, but we'll be getting right to work on implementing them ourselves, not to worry.

**Comment by typhonrt** [comment]
@Xystem4 Greets! Welcome to the Foundry VTT fold.. ;D I do hope the codebase I leave you and the RCOS team is pleasant to work with. I certainly welcome to opportunity to assist in as much knowledge transfer as seems reasonable. I'm certainly commenting all the code and making a final effort in improving readability. There are several avenues of exploration that I have set up for the RCOS team to explore as well. 

To everyone else possibly reading this. I have just made a commit that gets the FQL release candidate to very solid release candidate. While I will be restructuring code for readability at this point I have closed out all further feature / and revisions of existing functionality. I do believe I have got things to a very stable point. If you have the free time please install the latest version linked above and report back any findings.

**Comment by typhonrt** [comment]
Well.. https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/pull/51 is in... I feel like it's really stable at the moment. It would be great to get a weekend launch. I do however have to finish some code readability changes and full documentation. So a follow up PR shortly after `0.7.0` gets out the door.
