### ISSUE TITLE
Add Bug Reporter Flag to Manifest

### ISSUE THREAD

**Issue by anthonyronda** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#54]
Bug Reporter is a module for Foundry VTT that allows users to submit bugs without leaving Foundry!

https://github.com/League-of-Foundry-Developers/bug-reporter

Follow instructions for 0.8.3+

**Comment by lyndseytoft** [comment]
Hi I would like to be assigned to this!

**Comment by LukeLavan** [comment]
On the subject of inter-module compatibility, there was a comment regarding the incorporation of [foundryvtt-devMode](https://github.com/League-of-Foundry-Developers/foundryvtt-devMode) as well.

**Comment by anthonyronda** [comment]
@LukeLavan think you can write that as a separate Issue? If not I'll do it
