### ISSUE TITLE
randomly generate/choose a SampleTask

### ISSUE THREAD

**Issue by LukeLavan** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#56]
The following code snippet is responsible for the textbox that appears when the 'Add Objective' button (`add-new-task`) is clicked on a `quest-preview` document:

https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/blob/5478d0ef5f884a63b406e4e0e0ce6e59af153a27/modules/view/QuestPreview.js#L280-L308

Instead of using `ForienQuestLog.SampleTask` each time, the text hint displayed should be a different example each time at random.

In my opinion, the easiest way to do that would be to come up with a list of possible choices that is long enough to avoid frequent repeats and use `Math.random()` to pick one at random. I imagine that this list would be encoded within the locale files for each language, meaning languages might be able to have a different number of choices (locales relying on old translations can continue to use their one defined SampleText). Alternatively, we could come up with a number of 'slots' that should be sufficient to be the number of possible choices every language must have - in that case, multiple slots can contain the same string/a reference to one string (although this approach would raise questions of design and maintainability).

**Comment by LukeLavan** [comment]
Additionally, a cursory search through the repo suggested that `templates/partials/quest-form/task.html` might be relevant to this suggestion, but it actually appears to be vestigial.

**Comment by LukeLavan** [comment]
Seems only Contributors are allowed to put labels on issues, but this should have the `enhancement` label. For now I've put it in the title (at least until the appropriate label is applied).

**Comment by typhonrt** [comment]
Just as a note.. I actually took the sample task and abstract reward placeholders out of the `0.7.4` FQL release. This streamlines the GUI especially w/ repetitive data entry.  I think a better view of FQL is that it is a workhorse that GMs / users know how to drive than a creativity prompting tool. That being said I think this issue can be closed, but good first idea for sure.
