### ISSUE TITLE
Use devMode for debugging

### ISSUE THREAD

**Issue by LukeLavan** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#57]
The [foundryvtt-devMode](https://github.com/League-of-Foundry-Developers/foundryvtt-devMode) module can be used to safely leave debug code in the remote. This is useful for code readability and for future programmers debugging systems they didn't write.

Future code should make use of this. It may also be useful to go back and add debug code for already existing code.

**Comment by anthonyronda** [comment]
Discussed 30-06-2021, looking for suggestions on where to place logging

**Comment by typhonrt** [comment]
I suppose this is theoretically fine as long as there are no hard dependencies added to the module manifest. It really isn't a good idea to add extra module dependencies to FQL. I haven't looked into the `devMode` module, but a glance at the README suggests that it is enabled via a hook and is an adjacent module that is installed.

**Comment by LukeLavan** [comment]
> 
> 
> I suppose this is theoretically fine as long as there are no hard dependencies added to the module manifest. It really isn't a good idea to add extra module dependencies to FQL. I haven't looked into the `devMode` module, but a glance at the README suggests that it is enabled via a hook and is an adjacent module that is installed.

Correct; when the devMode hook fires, we register a flag that FQL will use. The intent is that developers can use this flag to determine whether logging actually goes into the console, but it's essentially just a user-set boolean - [see this example usage](https://github.com/League-of-Foundry-Developers/foundryvtt-devMode#step-2-read-that-value).

If the module is not installed, the hook simply never fires and any `console.log()` output dependent on the flag will not appear.

Seeing as how FQL currently makes very little use of `console.log()` in production, this would make very little change until proper logging is added into FQL.

**Comment by LukeLavan** [comment]
Closing the issue as there does not seem to be a need for this change without proper logging. We should probably avoid using `console.log` and devMode logging simultaneously. If FQL ever does add logging I recommend that this is used, but until then the change is not significant enough to warrant an open issue.
