### ISSUE TITLE
Create a macro compendium for FQL that contains macros w/ icons for common control actions.

### ISSUE THREAD

**Issue by typhonrt** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#58]
FQL can be controlled by macros. Instead of having users create their own w/ code snippets providing a macro compendium that contains all the options possible would be handy for many GMs / players. Players & GMs can drag and drop these macros to the hotbar to control FQL in a more convenient fashion than opening the module settings or copy / pasting the commands from a wiki. 

The nice thing about providing a macro compendium is that icons that represent the action can be set to the macros for a nice look and feel. Furthermore.. In a macro the `this` context is the macro itself, so it is possible to update the icon for the state of the module setting being modified, so toggle states can be represented with different images.

Examples of basic hooks that can be invoked to open the quest log and floating log.

```js
Hooks.call('ForienQuestLog.Open.QuestLog');
Hooks.call('ForienQuestLog.Open.QuestLogFloating');
```

All module settings can have macros as well. Here is one to show / hide tasks in the quest tracker:
```js
await game.settings.set('forien-quest-log', 'questTrackerTasks', !game.settings.get('forien-quest-log', 'questTrackerTasks'));
```

An example of the above macro swapping the macro image (swap actual images for module resources):
```js
const newState = !game.settings.get('forien-quest-log', 'questTrackerTasks');

await game.settings.set('forien-quest-log', 'questTrackerTasks', newState);

const img = newState ? 'systems/dnd5e/icons/skills/affliction_01.jpg' : 'systems/dnd5e/icons/skills/affliction_02.jpg';

await this.update({ img }, { diff: false });
```

**Comment by lyndseytoft** [comment]
I would like to take this on.

**Comment by typhonrt** [comment]
Awesome @lyndseytoft. This is really going to help users a lot. I'll list potential macros soon. It might make sense to make a GM related macro compendium and a user facing compendium that a GM  enables / makes visible to players / users. I'll make a list of macros that fit either category.

**Comment by lyndseytoft** [comment]
@typhonrt I look forward to seeing that list of macros soon, thank you.

**Comment by typhonrt** [comment]
I'll definitely get a list of all the macros posted here soon. Providing a macro compendium is definitely a big value added addition to FQL and glad you are interested in making this happen. Besides the mechanical aspects of pulling this together something to think about is the graphics / icon aspects that can be utilized. If anyone on the RCOS team has graphics design experience this is a great opportunity to design a nice icon set that can be attached to each macro.

**Comment by typhonrt** [comment]
I'll separate the macros by compendium type. There should be a GM related compendium and one for players.

There are a couple of macro types, but the main one that can be duplicated across all settings with boolean states is the following:
```
const newState = !game.settings.get('forien-quest-log', '<boolean setting to flip>');
await game.settings.set('forien-quest-log', 'questTrackerTasks', newState);
const img = newState ? 'modules/forien-quest-log/icons/macros/<setting name on>.jpg' : 'modules/forien-quest-log/icons/macros/<setting name off>.jpg';
await this.update({ img }, { diff: false });
```

There will be icon assets added to `icons/macros/<setting name on / off>` and such. Boolean setting macros will have an on & off state icon. The default state for the given setting will be the default icon associated in compendium / pack creation. It will auto-update to any current state on first press. 

The other category of macros are single button press macros. These will have a single icon to represent the macro in the hotbar which is assigned in compendium / pack creation. Some of these are basic hooks to invoke such as opening the quest log. A few other GM specific single state macros involve running DB migration and selecting the default abstract reward icon. 

---

The GM compendium... First the boolean macros which will follow the pattern above these setting names are listed below:
- allowPlayersAccept
- allowPlayersCreate
- allowPlayersDrag
- countHidden
- hideFQLFromPlayers
- notifyRewardDrop
- trustedPlayerEdit

Specific macros for single actions for the GM include:

DB Migration - runs all DB migration; documentation should indicate that the integer parameter can be set to run a specific migration level to max level migration:
`Hooks.call('ForienQuestLog.Run.DBMigration', 0);`

defaultAbstractRewardImage: This macro opens a FilePicker for the GM to select the default image assigned to new abstract rewards created in quests.
```
new FilePicker({
   type: 'image',
   
   callback: async (path) =>
   {
      await game.settings.set('forien-quest-log', 'defaultAbstractRewardImage', path);
   },
}).browse();
```

---------------

The player oriented macro compendium contains macros related to client settings. The reason to split it off into a separate compendium is that the GM compendium will be marked invisible and a GM can then make the player compendium visible / available for players. 

First the boolean macros which will follow the pattern above these setting names are listed below:
- enableQuestTracker

Next are the single state macros for opening the quest log / floating quest log:
open quest log - Opens the main quest log:
`Hooks.call('ForienQuestLog.Open.QuestLog');`

open floating quest log - Opens the main quest log:
`Hooks.call('ForienQuestLog.Open.QuestLogFloating');`

resetQuestTracker - resets the quest tracker position if hidden by window / size changes: 
`game.settings.set('forien-quest-log', 'resetQuestTracker', true);`
