### ISSUE TITLE
Improve quest tracker HUD

### ISSUE THREAD

**Issue by rlach** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#59]
Currently quest tracker can get unusable pretty quickly, especially if players create more than 2-3 quests that are active at once.
![image](https://user-images.githubusercontent.com/5655000/123549583-07a9b600-d76a-11eb-9811-0bd87ac4c5bf.png)

My suggestion is to add in star(or another) icon for quests that are in progress, next to other control icons. That could be used to set quest as being currently tracked. If there are no tracked quests keep current functionality. If there is at least 1 tracked quest show only tracked quests in the HUD.

Additionally currently clicking list of tasks for a quest and the quest title both bring user to the quest entry. It could be more useful if quest title would switch display of that quest on a click trough those modes:
normal mode => only show incomplete tasks => don't show tasks at all => back to normal.
Don't show tasks at all can already be achieved trough module settings, but it applies to all quests so it isn't very practical.

Also, it would be very cool if we had settings to auto-hide tracker during combat encounters.

Finally it would be amazing if we could minimize the tracker at any point if it's getting in the way, then restore it to usual size. It could be a button next to the "dragger" to used to move the window around.

**Comment by typhonrt** [comment]
So there are some current options available. There is a configuration option to just show quest names and hide the tasks.  You can access that in the settings under "Show Quest Tracker Tasks". 

You can also setup the following macros in the hot bar to enable / disable tasks and to show / hide the quest tracker:

show / hide tasks:
`await game.settings.set('forien-quest-log', 'questTrackerTasks', !game.settings.get('forien-quest-log', 'questTrackerTasks'));`

show / hide quest tracker:
`await game.settings.set('forien-quest-log', 'enableQuestTracker', !game.settings.get('forien-quest-log', 'enableQuestTracker'));`

There won't be any sort of interaction with the combat tracker or other modules any time soon, so you'll have to enable / disable the quest tracker through a macro when you like.  

You're general request is why the enhancement issue for creating a macro compendium for FQL w/ premade macros that also feature nice icons is on the horizon:
https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/issues/58

I'll look into another configuration option to set the task list to: all tasks, all incomplete tasks, visible incomplete tasks. This will be a configuration option though as there is no easy way to keep state regarding the quest tracker itself for individual quests.

**Comment by rlach** [comment]
Thanks for the workarounds, they do help. 

> You can also minimize the amount of quests in the tracker as the tracker only shows active quests. Perhaps try and only have one or two active quests at once vs three or more.
This is what we were trying to do, but sometimes players start on something, but then for some time cannot continue. They would like to pause the quest so it would go back to available, but all options that exist are complete, fail or inactive the quest, and the last option puts the quest out of their sight completely. 

That's why I suggested adding "track this quest" button, but having transition form active to available would be decent replacement too.

>  This will be a configuration option though as there is no easy way to keep state regarding the quest tracker itself for individual quests.
I wonder then, if it's possible to have quest tracker state be in sync with floating quest log window. It has functionality to fold tasks, per quest, which persists between reloads. So quest tracker could reflect the state of that window(maybe as an option in configuration).

**Comment by Shuggaloaf** [comment]
>They would like to pause the quest so it would go back to available, but all options that exist are complete, fail or inactive the quest

Hey @rlach there's a pretty simple work-around for this but it would involve 1 click from you. Have them/you mark as inactive, then you (GM) goes to inactive tab and marks as available. Not perfect but minimal effort and gets the job done. Hope that was helpful! :-)

**Comment by typhonrt** [comment]
The QuestTracker is much improved. It's checked in a recent PR, but not released. Works in a very similar way that @rlach described. It synchronizes between the floating quest log (smaller window) and quest tracker and allows clicking the quest name to hide / show tasks individually for each quest. 
Pending release.

**Comment by typhonrt** [comment]
Shipped in `0.7.4` which is now available.
