### ISSUE TITLE
Quests descriptions are not updating when modified

### ISSUE THREAD

**Issue by droza888** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#6]
I create quests, but am then unable to update the quest descriptions. I make changes, but the changes don't save. The other fields seem to update okay.  I'm on Foundry 0.7.9, with Quest Log 0.5.3.

EDIT: I discovered the problem - I wasn't clicking the save button within the Description editor. Feel free to delete this issue.

**Comment by xdy** [comment]
Closing as per previous comment.
