### ISSUE TITLE
[DISCUSSION] Important note on FQL support on version 9 of Foundry and the `0.7.9` update

### ISSUE THREAD

**Issue by typhonrt** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#6]
Greets folks. 

There is an important update aspect to upgrading to version 9 of Foundry and FQL functionality that needed to be disabled. The `0.7.9` release of FQL only disables this functionality if you upgrade to version 9 of Foundry and otherwise there are no changes. 

There was a late breaking change to v9 of Foundry ~10 days before the v9 stable release that causes FQL to crash on v9. This feature set is the "document linking / entity content linking" of quests. The novel implementation to support this feature is no longer available in v9. To make sure folks can upgrade to v9 right away and still use FQL the best option was to disable "document linking" for quests. While this is somewhat annoying for folks that utilize this functionality everything else about FQL still works fine on v9. If "document linking" of quests is a feature that you use a lot in your worlds you may consider not upgrading to v9 until the new quest log module is available.

An interim solution is to change document links as you come across them from `@Quest[ID]` to `@JournalEntry[ID]`; basically renaming the `@Quest` to `@JournalEntry`. Alas this is a manual step wherever you come across the defunct @Quest link. 

I am working on a new quest log module that is a continuation of FQL that hopefully will be ready toward the end of Q1 '22. There will be an easy upgrade transition to the new quest log and all of your quest data will transfer over smoothly. I will figure out the best way to enable / implement quest "document linking" again in the new quest log module. If you'd like to keep updated on the progress and availability of the new quest log module please join the [TyphonJS Discord server](https://discord.gg/mnbgN8f).

Happy questing as always!

**Comment by keyxmakerx** [comment]
Will the new FQL be able to import the old stuff?

**Comment by typhonrt** [comment]
Hi @keyxmakerx. Indeed the new quest log module will import / transfer data from FQL.

**Comment by typhonrt** [comment]
Greets... The issue of quest linking is resolved w/ the public release of FQL 0.7.10 for Foundry v9 & v10.
