### ISSUE TITLE
Unexpected behavior in quest log when given extremely long quest names

### ISSUE THREAD

**Issue by Xystem4** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#60]
**Module Version:** v0.7.3

**Describe the bug**
The quest log doesn't take into account the possibility of ridiculously long text quest names, and so ends up having overlapping text, text going off the screen, etc. when faced with one.

Also, selecting a quest becomes odd when this happens because it selects the highest quest whose text you are over, which isn't necessarily the quest whose bounding box you are over (making the top quest impossible to select, sometimes)

Note that other areas of the module _do_ properly adjust the displayed height for long quest names. Both the floating quest window and the Delete Quest dialog adjust vertically (but _not_ horizontally, ironically).

**To Reproduce**
1. Go to Quest Log
2. Click on Add new Quest
3. In the Quest Name textbox, put in a name that will be over 2 lines long (at least 3 strings of >80ish characters each, separated by spaces).
4. Add to Quest Log, and observe the formatting. Repeat with another quest to observe overlapping text

**Expected behavior**
There are two ways I see how the quest log could reasonably handle this. It could adjust the displayed height of the quest in the quest list automatically (as it does with the width), or it could impose a limit on how long a quest's name can be, preventing the user from giving a quest a name that would be over two lines long when displayed.

**Screenshots**
How a single quest with an overly long name appears in the quest log (the name is vertically centered, so about half the lines go above the window):
![one long name](https://user-images.githubusercontent.com/65842664/123556420-22276380-d759-11eb-82d7-ab0de3c6c542.png)

How many quests with overly long names appear together in the quest log:
![many long quests](https://user-images.githubusercontent.com/65842664/123556521-a843aa00-d759-11eb-8d33-2d74850bbee9.png)

How the floating quest window appears with overly long names (there are more characters being cut off on the right):
![floating quest window long names](https://user-images.githubusercontent.com/65842664/123557474-f3ac8700-d75e-11eb-9b22-ae3df2beb664.png)

How the Delete Quest dialog appears with a long quest name (cut off on the right edge, again):
![delete quest dialog long name](https://user-images.githubusercontent.com/65842664/123557486-045cfd00-d75f-11eb-989d-4fd1a91fe7b7.png)

**Browser:**
Chrome Version 91.0.4472.114

**Foundry Version:** 
0.8.8

**Game System:** 
DnD5e 1.3.6

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by typhonrt** [comment]
Definitely something to fix. I suggest a cutoff in input length of 64 characters or less. Also font size scaling to reduce font size after 24 characters then once again at 48 characters. Additionally limiting the flex layout of the quest name field to a certain size and have longer quest names grow the `li` element vertically. In the near future other text entry fields for quest location and type may be added, so making sure there is space for additional text entries to the right of the quest name is pertinent.

**Comment by jinh5** [comment]
I think this is an interesting bug and would like to take it up.

**Comment by typhonrt** [comment]
This was a simple fix adding max-length to input html elements. I also spent a bit of time making sure no long strings can interrupt the GUI in all data entry fields.

**Comment by typhonrt** [comment]
Shipped in `0.7.4` which is now available.
