### ISSUE TITLE
Hidden subquests can be seen by players through the Floating Quest Window interface

### ISSUE THREAD

**Issue by lpinch** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#64]
**Module Version:** v0.7.3

**Describe the bug**
Players can see hidden (inactive) subquests through the Floating Quest Window

**To Reproduce**
1. Create a quest and a subquest for it
2. Make the quest active
3. Login through a player account
4. See that the player cannot see the inactive subquest through the normal ui but can using the Floating Quest Window feature on the right toolbar.

**Expected behavior**
The subquest should be hidden from the player.

**Screenshots**
![image](https://user-images.githubusercontent.com/86579209/123565414-11a8d480-d7bd-11eb-8fa4-41e35eb76a64.png)

**Browser:**
 - 

**Foundry Version:** 
0.8.8

**Game System:** 
pf2e

**Comment by typhonrt** [comment]
Hi @lpinch. Thanks for the report. I believe we'll have a `0.7.4` update out this week which will address this issue. 

In the meantime until the update if you have a session while slightly inconvenient you can go to the subquest and in the manage section set the default permission to `None`. This will definitely hide the subquest from all players regardless of it's current state. What you reported is a subquest that is in the inactive category that is showing to players. IE a non-active quest which is supposed to be hidden of course until it is activated. By explicitly setting the subquest to default permission `None` this will also effectively hide it though you'll have to remember when you make the subquest active / hit the play button to also go and set the default permission back to `Observer` so your players have the permissions to see the quest.

**Comment by typhonrt** [comment]
Shipped in `0.7.4` which is now available.
