### ISSUE TITLE
Testing FQL Bug Reporter

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#70]
**Feedback Type**: Bug
 
**Core:** 0.8.7
**System:** dnd5e v1.3.5
**Module Version:** forien-quest-log v0.7.3
 
**Description**:
Testing the changes made for issue #54 before committing. If you see this please ignore. :)

**Comment by lyndseytoft** [comment]
Hi! This is the bug report I made to test the changes for #54, it seems as though the changes work, so if you wouldn't mind closing/deleting this issue I would appreciate it! :D
