### ISSUE TITLE
Odd behavior with textbox edit button

### ISSUE THREAD

**Issue by Xystem4** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#73]
**Module Version:** v0.7.3

**Describe the bug**
When creating a new quest, to edit either the Quest Description or the GM Notes, the "edit button" must first be pressed. Before pressing the button, it is only visible while the cursor is over the text box. However, after editing and saving the text box, the button stays visible regardless of cursor placement. This is inconsistent with both the behavior before first editing the textboxes, and the behavior _after_ editing the textboxes at any other time than first creation of a quest (so, if editing an already existing quest, the edit button does disappear when the cursor is not over the textbox, even after editing the textbox).

**To Reproduce**
1. Go to Quest Log
2. Click on Add new Quest
3. Click the edit button for the Quest Notes Textbox
4. Add some text to the textbox, and click the save button
5. Move your cursor away from the textbox, and observe that the edit button remains visible

**Expected behavior**
I would expect the button to become invisible once the cursor is no longer over the textbox, as it does elsewhere in the module (particularly since it can end up obscuring text written in the box that ends up beneath the button).

**Screenshots**
before editing any text box (my cursor is invisible here, but it's at the very top right of the screen)
![Screenshot (25)](https://user-images.githubusercontent.com/65842664/124015729-f7d0e280-d9b2-11eb-891a-5f89d9b40887.png)
after editing the Quest Description textbox (my cursor is again invisible, but at the top right of the screen)
![Screenshot (26)](https://user-images.githubusercontent.com/65842664/124015849-0ae3b280-d9b3-11eb-8739-16460d116204.png)

**Browser:**
Chrome Version 91.0.4472.114

**Foundry Version:** 
0.8.8

**Game System:** 
DnD5e 1.3.6

**Comment by typhonrt** [comment]
This whole app / experience potentially goes away if the QuestDetails / QuestPreview is immediately brought up for the user to edit. I described more in the Leagues' Discord chat.

**Comment by jinh5** [comment]
Could I be assigned to reproducing this behavior?

**Comment by typhonrt** [comment]
The QuestForm is no longer in the add quest work flow and removed.

**Comment by typhonrt** [comment]
Shipped in `0.7.4` which is now available.
