### ISSUE TITLE
Players seeing GM tooltips for locked quest icon

### ISSUE THREAD

**Issue by Xystem4** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#74]
**Module Version:** v0.7.3

**Describe the bug**
When a player hovers their cursor over the locked (or unlocked) icon next to a reward, it will display the tooltip "Reward is locked. Click to unlock." (or the reverse if the quest is unlocked). These are the same tooltips displayed to the GM (which is good, they should be displayed there), but they are not correct or relevant for the player.

**To Reproduce**
1. Go to Quest Log, as a player
2. Click on an existing quest with rewards
3. Hover over the locked or unlocked icon to the right of a reward
4. Observe the tooltip, matching that seen by the GM

**Expected behavior**
I would expect either no tooltip to be shown to the player, or for a more relevant tooltip to be shown. Possibly just "Reward is locked." / "Reward is unlocked.", maybe with additional information on what that means added to the end.

**Browser:**
Chrome Version 91.0.4472.114

**Foundry Version:** 
0.8.8

**Game System:** 
DnD5e 1.3.6

**Comment by LukeLavan** [comment]
Relevant snippet of code: https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/blob/5478d0ef5f884a63b406e4e0e0ce6e59af153a27/templates/partials/quest-preview/details.html#L199-L203

**Comment by typhonrt** [comment]
Good idea.. There is a `canEdit` field which can be used to pick two different tooltips from the template itself. It might make more sense in creating the tooltip in `Enrich.quest` that prepares the tooltip to be displayed in advance of rendering the template.

**Comment by typhonrt** [comment]
Shipped in `0.7.4` which is not available.
