### ISSUE TITLE
Allow checkboxes in the floating quest window to be checked

### ISSUE THREAD

**Issue by jinh5** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#75]
Currently, the floating quest window is just for viewing but I think it would be helpful to allow the checkboxes to be checked on/off and have the status on the quest log updated too. The floating quest window would be an easy way to update the completion status of an objective.

**Comment by anthonyronda** [comment]
Discussed 30-06-2021, still needs to be scoped

**Comment by LukeLavan** [comment]
related to #59

**Comment by typhonrt** [comment]
There is a major improvement to the QuestTracker incoming with my final big feature PR that solves #59, but I'll leave the idea of interacting with the task / objectives from the QuestTracker to RCOS.

**Comment by typhonrt** [comment]
Released with `0.7.6` which is available now.
