### ISSUE TITLE
Add contributor guidelines

### ISSUE THREAD

**Issue by LukeLavan** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#76]
As more people contribute to the project, it would be helpful to have a [CONTRIBUTING.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) to point to.
Off the top of my head, some items that could be included:

- use devMode for debugging instead of console.log()
- recommend eslint and style guide
- pull request template/recommended inclusions

**Comment by lyndseytoft** [comment]
I would like to take this on with Luke if possible.
