### ISSUE TITLE
QuestLog.render(true); Macro not working since update (instructions)

### ISSUE THREAD

**Issue by rnarducci** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#80]
**Module Version:** v0.7.3

**Describe the bug**
Since updating to 0.7.3 (on Foundry version 0.8.7) my macro to open the quest log does not work. The macro is QuestLog.render(true);
Gives the error that QuestLog is not defined.

**To Reproduce**
1. Updated to 0.7.3
2. Used the script macro QuestLog.render(true);

**Expected behavior**
Up until now it opened the quest log interface.

**Screenshots**
![image](https://user-images.githubusercontent.com/47222373/124334927-3d7dde80-db5e-11eb-94fc-bf7d37cc2aa1.png)

**Browser:**
Tested on Firefox Nightly and Google Chrome.

**Foundry Version:** 0.8.7

**Game System:** DnD5e - Fifth Edition System

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by rnarducci** [comment]
Found a temporary workaround for anyone else with this problem:
`game.modules.get('forien-quest-log').public.questLog.render(true)`

**Comment by typhonrt** [comment]
Hi @rnarducci. Indeed the documentation needs to be updated. This isn't a bug. Forien's Quest Log no longer exposes resources in the global space. The recommended way to access both the quest log and quest floating log is the following hooks:

`Hooks.call('ForienQuestLog.Open.QuestLog');`

`Hooks.call('ForienQuestLog.Open.QuestLogFloating');`

Quite likely the temporary solution you found is going away soon, but the above will work.

**Comment by rnarducci** [comment]
@typhonrt Thanks for the reply and clarification! I have changed my macro to what you have here.

**Comment by typhonrt** [comment]
I have updated the package description in Foundry to point to the [new wiki](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/wiki) location in this repo. I will certainly update the wiki with a lot more information over the next couple of weeks, but have added this pertinent info right now. 

I'll close this issue for the time being though.
