### ISSUE TITLE
Can't Open Quest Log

### ISSUE THREAD

**Issue by Artetsu** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#88]
**Module Version:** 0.7.3

**Describe the bug**
Can't open the quest log

**Screenshots**
![Quest Log Error](https://user-images.githubusercontent.com/36137698/124662069-988a3b00-dea8-11eb-97a3-4d9fd3ef9cb2.PNG)

**Browser:**
Safari

**Foundry Version:** v0.8.8

**Game System:** DnD 5e 1.3.6

**Comment by typhonrt** [comment]
This is an interesting issue as it indicates quite likely something else is wrong external to Forien Quest Log.  

The line that fails is `if (actor.isGM) { continue; }` indicating that there is an `undefined` user in `game.users` which are all the users (players & GMs).  I see that you are probably using many other modules as libwrapper is involved in the error stack. Can you try to turn off as many other modules as possible and see if the problem remains. The next thing to try is to create a new world and only install Forien Quest Log. 

As mentioned the error stack and what is failing is not exactly an issue of FQL itself, but indicates another serious problem with your world and internal state of Foundry itself. There is a big possibility that turning off all other modules may not fix this issue for this particular world. 

I have read of issues with something possibly to do with libwrapper on 0.8.8 that is still an unknown situation that is hard to reproduce about the internal state of Foundry being inconsistent or something like that. Not sure if it is libwrapper related or Foundry itself...

**Comment by Artetsu** [comment]
Gotcha. It might have been due to me deleting a user that was previously in the quest logs. I will try re-introducing the exact username to see if it fixes the issue or not. Thank you for your attention!

**Comment by typhonrt** [comment]
Yes.. This indeed is the issue and I have been able to reproduce it by setting a quest and thereby the backing journal entry with a specific permission for a user that is then deleted from the game. So this quite possibly is a bug in FQL. I was under the impression that the permissions returned from a document / journal entry would be correct for the game state and updated when a user is deleted, but it appears that permissions data is not updated in the Foundry DB when a user is deleted and so there can be stale data that one has to ignore. 

I will certainly add in protection for this case in `0.7.4` which will launch shortly. Thanks so much for filing this issue as it's a corner case that I was not aware of presently.

In the meantime sadly adding a new user with the same name likely won't fix the issue as the internal ID of the old user is what is used in the lookup in `game.users`. If you can delete this quest / backing journal entry by showing the hidden _fql_quests journal entries folder and then deleting the journal entry then things will work again. On the version of FQL you are using FQL shouldn't try to load quest data until you actually show the quest log, so you should be able to access the module settings / show the _fql_quests journal entry folders and delete the journal entry for the quest that was assigned to the deleted user and things should work again.

**Comment by typhonrt** [comment]
Another thing you can do without deleting the quest is to explicitly set the permissions of the journal entry in question. Context click the journal entry and select set 'configure permissions' / hit save and that should fix things without needed to delete the quest.

**Comment by typhonrt** [comment]
Got it fixed.. Thanks again for the report. Let me know if you need any more info on how to fix things / workaround your current situation w/ FQL `0.7.3`.. The latest `0.7.4` should be out in a couple of days.

**Comment by typhonrt** [comment]
Shipped in `0.7.4` which is not available.
