### ISSUE TITLE
[BUG] _fql_quests folder available as an option for players to save Journal Entries in  

### ISSUE THREAD

**Issue by Norc** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#9]
**Module Version:** v0.5.3

**Describe the bug**
What looks to be a placeholder non-user facing older is visible to players as an option to save journals in. I am certain the top option is from Forien's Quest Log:

![image](https://user-images.githubusercontent.com/64667579/103675490-02537780-4f4e-11eb-8f15-5df1d8d9040a.png)

**To Reproduce**
1. In a world with an active Quest set up, connect as a player
2. Create a new Journal Entry (make sure player has permissions to do so)
3. Attempt to save the JE in a folder, observe the top option.

I assume this is a bug because I can't see the folder in the JE sidebar tab itself, just here.

**Expected behavior**
This folder should not be visible as an option to save a journal entry in because it is not user-facing.

**Screenshots**
![image](https://user-images.githubusercontent.com/64667579/103675749-4c3c5d80-4f4e-11eb-9ffe-bf819093e38b.png)

**Browser:**
 Chrome

**Foundry Version:** 
0.7.9 (but it's on Atropos' machine so who knows)
**Game System:** 
5E 1.2.0 (but it's on Atropos' machine so who knows
**Additional context**
Only 4 other modules installed, but Foundry and 5E may have non-standard code in it.

**Comment by typhonrt** [comment]
This is fixed in the latest unreleased version of FQL... 

![image](https://user-images.githubusercontent.com/311473/122655414-f24be080-d106-11eb-96bf-b5055ce8c618.png)
