### ISSUE TITLE
[BUG] Pressing ESC key while editing GM Notes breaks all links

### ISSUE THREAD

**Issue by adacosta92** [League-of-Foundry-Developers/foundryvtt-forien-quest-log#98]
**Module Version:** v0.7.3

**Describe the bug**
Pressing ESC key while editing GM Notes breaks all Foundry links

**To Reproduce**
1. Create a quest/open a quest
2. navigate to GM Notes and edit them. 
3. Drag in a link from a compendium and save
4. Edit again and press "ESC"

**Expected behavior**
Save + stop editing the text.

**Screenshots**
![chrome_GcqwhNt1oO](https://user-images.githubusercontent.com/67127175/125725513-c1d76500-4bf6-458f-984d-62158ed345b3.png)

**Browser:**
 - Chrome

**Foundry Version:** 
0.8.8

**Game System:** 
dnd5e

**Additional context**

**Comment by typhonrt** [comment]
Hi @adacosta92. Pressing `Esc` doesn't save any editing. It's a quick way to back out of editing and not save anything. 

If you want to save your edits. `Ctrl-S` is the key combo to save your edits and end editing. 

I have tried several combos of pressing `Esc` and it doesn't appear to break any of the links. It simply doesn't save any edits that are made. 

This can certainly be made clearer in any updated wiki / documentation, but at this time I don't believe this is a bug. 

Please provided additional commentary if you like before I mark this issue as `wontfix` / `invalid`.

**Comment by adacosta92** [comment]
That's strange, because it happened for me with all other modules off. I'll do some further testing.

**Comment by adacosta92** [comment]
Yup, still happening. Screenshot with what it is exactly that I mean.
![](https://i.imgur.com/tQG6Zcy.jpeg)

**Comment by typhonrt** [comment]
Hi @adacosta92 thanks for the extra info. Indeed this is special handling in FQL to provide the `Esc` action. What happened is that the content was being reset to the initial content that already was enhanced (HTML for content links). This should work in the `0.7.5` release forthcoming. I'll push it out today as this is issue is an annoyance. I also added small quality of life aspects like handling `Esc` to cancel all single line input field edits.

**Comment by typhonrt** [comment]
Released `0.7.5` live now.
